SET CLIENT_ENCODING TO 'ISO-8859-1';

start transaction;

CREATE TABLE actions (
	action_js CHARACTER VARYING(128) NULL,
	affichage_js CHARACTER VARYING(32) NOT NULL DEFAULT '',
	competence INT NOT NULL DEFAULT 0,
	condition TEXT NOT NULL,
	description CHARACTER VARYING(255) NOT NULL,
	id INT NOT NULL,
	image CHARACTER VARYING(32) NOT NULL DEFAULT '',
	nom CHARACTER VARYING(32) NOT NULL DEFAULT '',
	nom_court CHARACTER VARYING(32) NULL,
	pa SMALLINT NOT NULL DEFAULT 0,
	parole SMALLINT NOT NULL DEFAULT 0,
	pm SMALLINT NOT NULL DEFAULT 0,
	script CHARACTER VARYING(64) NOT NULL DEFAULT '',
	type INT NOT NULL DEFAULT 0,
	xp SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_actions PRIMARY KEY (id)
);

CREATE TABLE annonces (
	auteur INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	langues TEXT NOT NULL,
	nom_auteur CHARACTER VARYING(40) NOT NULL,
	taverne INT NOT NULL DEFAULT 0,
	texte CHARACTER VARYING(255) NOT NULL,
		CONSTRAINT pk_annonces PRIMARY KEY (id)
);

CREATE TABLE armes (
	afficher SMALLINT NOT NULL DEFAULT 1,
	artefact SMALLINT NOT NULL DEFAULT 0,
	bonus SMALLINT NOT NULL DEFAULT 0,
	comp CHARACTER VARYING(15) NOT NULL DEFAULT '',
	competence_min CHARACTER VARYING(255) NULL,
	de SMALLINT NOT NULL DEFAULT 0,
	degats SMALLINT NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	deux_mains SMALLINT NOT NULL DEFAULT 0,
	dex INTEGER NOT NULL DEFAULT 0,
	dossier INTEGER NOT NULL DEFAULT 0,
	effets TEXT NOT NULL,
	enchantable SMALLINT NOT NULL,
	enco INTEGER NOT NULL DEFAULT 0,
	fichier_degats CHARACTER VARYING(30) NOT NULL DEFAULT '',
	force INTEGER NOT NULL DEFAULT 0,
	genre SMALLINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	image CHARACTER VARYING(50) NOT NULL,
	intel INTEGER NOT NULL DEFAULT 0,
	location TEXT NULL,
	maudit SMALLINT NOT NULL DEFAULT 0,
	niveau SMALLINT NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	poids INTEGER NOT NULL DEFAULT 0,
	portee SMALLINT NOT NULL DEFAULT 1,
	precis SMALLINT NOT NULL DEFAULT 0,
	prix INTEGER NOT NULL DEFAULT 0,
	race CHARACTER VARYING(10) NOT NULL DEFAULT '',
	sol INTEGER NOT NULL DEFAULT 0,
	sorts_aut SMALLINT NOT NULL DEFAULT 0,
	type CHARACTER VARYING(10) NOT NULL DEFAULT '',
	type_bonus SMALLINT NOT NULL DEFAULT 0,
	type_img CHARACTER VARYING(30) NOT NULL DEFAULT '',
	type_mun INTEGER NOT NULL DEFAULT 0,
	vendeur CHARACTER VARYING(20) NOT NULL DEFAULT '',
		CONSTRAINT pk_armes PRIMARY KEY (id)
);

CREATE TABLE artefacts (
	camoufle SMALLINT NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	id INTEGER NOT NULL DEFAULT 0,
	porte INTEGER NOT NULL DEFAULT 0,
	type CHARACTER VARYING(20) NOT NULL DEFAULT '',
	x INT NOT NULL DEFAULT 0,
	y INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_artefacts PRIMARY KEY (id,type)
);

CREATE TABLE assoc_coffre_equipement (
	idArme SMALLINT NULL,
	idCoffre INT NOT NULL,
	identifiantEquipement INT NOT NULL,
	idObjet SMALLINT NULL,
	idParure SMALLINT NULL,
	niveauEnchantement SMALLINT NULL,
	quantite SMALLINT NULL DEFAULT 1,
	solidite SMALLINT NULL,
		CONSTRAINT pk_assoc_coffre_equipement PRIMARY KEY (identifiantequipement)
);

CREATE TABLE assoc_habitations_perso (
	idHabitation INT NOT NULL,
	idPerso SMALLINT NOT NULL,
	status CHARACTER VARYING(32) NOT NULL DEFAULT '',
		CONSTRAINT pk_assoc_habitations_perso PRIMARY KEY (idhabitation,idperso)
);

CREATE TABLE assoc_relais_vehicule (
	idRelais INT NOT NULL,
	idVehicule INT NOT NULL,
		CONSTRAINT pk_assoc_relais_vehicule PRIMARY KEY (idrelais,idvehicule)
);

CREATE TABLE attente_login (
	acces BIGINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_attente_login PRIMARY KEY (perso)
);

CREATE TABLE audiences (
	auteur INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	langues TEXT NOT NULL,
	royaume INTEGER NULL,
	sujet CHARACTER VARYING(255) NOT NULL,
	texte TEXT NOT NULL,
	ville INTEGER NULL,
		CONSTRAINT pk_audiences PRIMARY KEY (id)
);

CREATE TABLE avertissements (
	date BIGINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	mj INTEGER NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL DEFAULT 0,
	raison CHARACTER VARYING(255) NOT NULL,
		CONSTRAINT pk_avertissements PRIMARY KEY (id)
);

CREATE TABLE bannis (
	autorise SMALLINT NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL DEFAULT 0,
	ville INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_bannis PRIMARY KEY (perso,ville)
);

CREATE TABLE batiments (
	avancement CHARACTER VARYING(128) NOT NULL DEFAULT '',
	banniere SMALLINT NOT NULL DEFAULT 0,
	chantier SMALLINT NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	hauteur SMALLINT NOT NULL DEFAULT 1,
	id BIGINT NOT NULL,
	id_template BIGINT NOT NULL DEFAULT 0,
	image CHARACTER VARYING(50) NULL,
	largeur SMALLINT NOT NULL DEFAULT 1,
	limite_action BIGINT NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(45) NOT NULL DEFAULT '',
	param BIGINT NOT NULL DEFAULT 0,
	terrain BIGINT NOT NULL,
	type INTEGER NOT NULL DEFAULT 0,
	ville SMALLINT NOT NULL DEFAULT 0,
	x INT NOT NULL DEFAULT 0,
	y INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_batiments PRIMARY KEY (id)
);

CREATE TABLE bonus_equip (
	classe CHARACTER VARYING(15) NOT NULL DEFAULT '',
	id CHARACTER VARYING(20) NOT NULL DEFAULT '',
	id_auto INT NOT NULL,
	param SMALLINT NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_bonus_equip PRIMARY KEY (id_auto)
);

CREATE TABLE bugs (
	avancement SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(255) NOT NULL,
	id SMALLINT NOT NULL,
	nom CHARACTER VARYING(50) NOT NULL DEFAULT '',
	solution TEXT NOT NULL,
		CONSTRAINT pk_bugs PRIMARY KEY (id)
);

CREATE TABLE carte (
	couleur CHARACTER VARYING(6) NOT NULL DEFAULT '',
	id INT NOT NULL DEFAULT 0,
	x INT NOT NULL DEFAULT 0,
	y INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_carte PRIMARY KEY (id,x,y)
);

CREATE TABLE cartes (
	description TEXT NOT NULL,
	fichier CHARACTER VARYING(64) NOT NULL DEFAULT '',
	fichierPJ CHARACTER VARYING(64) NOT NULL DEFAULT '',
	id INT NOT NULL,
	modif_mvt CHARACTER VARYING(64) NOT NULL DEFAULT 'N',
	modif_pamax SMALLINT NULL,
	modif_vue CHARACTER VARYING(64) NOT NULL DEFAULT 'N',
	nom CHARACTER VARYING(64) NOT NULL DEFAULT '',
	saison SMALLINT NOT NULL DEFAULT 0,
	type SMALLINT NOT NULL DEFAULT 0,
	visible SMALLINT NOT NULL DEFAULT 0,
	x INT NOT NULL DEFAULT 0,
	x_max INT NULL,
	x_min INT NULL,
	y INT NOT NULL DEFAULT 0,
	y_max INT NULL,
	y_min INT NULL,
		CONSTRAINT pk_cartes PRIMARY KEY (id)
);

CREATE TABLE chapitres_faq (
	id SMALLINT NOT NULL,
	nom CHARACTER VARYING(50) NOT NULL DEFAULT '',
	parent SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_chapitres_faq PRIMARY KEY (id)
);

CREATE TABLE chroniques (
	chapitre INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	image CHARACTER VARYING(100) NOT NULL DEFAULT '',
	legende CHARACTER VARYING(50) NOT NULL DEFAULT '',
	nom CHARACTER VARYING(50) NOT NULL DEFAULT '',
	perso INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
		CONSTRAINT pk_chroniques PRIMARY KEY (chapitre,perso)
);

CREATE TABLE chrontasks (
	description CHARACTER VARYING(255) NOT NULL,
	function CHARACTER VARYING(45) NOT NULL DEFAULT '',
	groupe INT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	nextexec TIMESTAMP NOT NULL,
	nom CHARACTER VARYING(45) NOT NULL DEFAULT '',
	parameters TEXT NOT NULL,
	timeinterval TIMESTAMP NULL,
		CONSTRAINT pk_chrontasks PRIMARY KEY (id)
);

CREATE TABLE coffres (
	contenanceActuelle INT NOT NULL,
	coutAmeliorationCoffre INT NOT NULL DEFAULT 1000,
	descriptionCoffre CHARACTER VARYING(200) NOT NULL DEFAULT 'Un coffre.',
	idCoffre INT NOT NULL,
	idHabitation INT NOT NULL,
	niveauCoffre SMALLINT NOT NULL DEFAULT 0,
	niveauCoffreMax SMALLINT NOT NULL DEFAULT 2,
	nomCoffre CHARACTER VARYING(40) NOT NULL DEFAULT 'Coffre',
		CONSTRAINT pk_coffres PRIMARY KEY (idcoffre)
);

CREATE TABLE competences (
	carac CHARACTER VARYING(8) NOT NULL DEFAULT '',
	description TEXT NOT NULL,
	dossier INTEGER NULL DEFAULT 0,
	gain1 REAL NOT NULL DEFAULT 0,
	gain2 REAL NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	image CHARACTER VARYING(64) NOT NULL DEFAULT '',
	max_autorise_default INT NOT NULL,
	mod_con REAL NOT NULL DEFAULT 0,
	mod_dex REAL NOT NULL DEFAULT 0,
	mod_exp REAL NOT NULL DEFAULT 0,
	mod_force REAL NOT NULL DEFAULT 0,
	mod_intel REAL NOT NULL DEFAULT 0,
	mod_per REAL NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(32) NOT NULL DEFAULT '',
	nomcourt CHARACTER VARYING(15) NOT NULL DEFAULT '',
	param1 CHARACTER VARYING(64) NOT NULL DEFAULT '',
	param2 CHARACTER VARYING(64) NOT NULL DEFAULT '',
	seuil REAL NOT NULL DEFAULT 0,
	theme INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_competences PRIMARY KEY (id)
);

CREATE TABLE competences_assoc (
	competence BIGINT NOT NULL,
	max_autorise INT NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL,
	valeur INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_competences_assoc PRIMARY KEY (competence,perso)
);

CREATE TABLE competencethemes (
	description CHARACTER VARYING(64) NOT NULL DEFAULT '',
	id INTEGER NOT NULL,
	nom CHARACTER VARYING(32) NOT NULL DEFAULT '',
		CONSTRAINT pk_competencethemes PRIMARY KEY (id)
);

CREATE TABLE comptes_banques (
	code CHARACTER VARYING(6) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(128) NOT NULL DEFAULT '',
	id INT NOT NULL,
	perso INTEGER NOT NULL DEFAULT 0,
	royaume INTEGER NOT NULL DEFAULT 0,
	solde INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_comptes_banques PRIMARY KEY (id)
);

CREATE TABLE connectes (
	date BIGINT NOT NULL DEFAULT 0,
	mj SMALLINT NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(50) NOT NULL DEFAULT '',
	perso INTEGER NOT NULL DEFAULT 0,
	royaume INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_connectes PRIMARY KEY (perso)
);

CREATE TABLE creatures (
	bloque_regen SMALLINT NOT NULL DEFAULT 0,
	cible1 INT NULL,
	cible2 INT NULL,
	cible3 INT NULL,
	cible4 INT NULL,
	gold INTEGER NOT NULL DEFAULT 0,
	IA INT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	naissance BIGINT NOT NULL DEFAULT 0,
	or_ca INTEGER NOT NULL DEFAULT 0,
	or_hb INTEGER NOT NULL DEFAULT 0,
	or_ithoria INTEGER NOT NULL DEFAULT 0,
	or_kohr INTEGER NOT NULL DEFAULT 0,
	or_pe INTEGER NOT NULL DEFAULT 0,
	pm SMALLINT NOT NULL DEFAULT 0,
	prochain_tour BIGINT NOT NULL DEFAULT 0,
	pv SMALLINT NOT NULL DEFAULT 0,
	reste_mouvement SMALLINT NOT NULL DEFAULT 0,
	sorts TEXT NULL,
	type BIGINT NOT NULL,
	ville INTEGER NULL,
	volonte SMALLINT NOT NULL DEFAULT 0,
	x INT NOT NULL DEFAULT 0,
	y INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_creatures PRIMARY KEY (id)
);

CREATE TABLE details_perso (
	aime TEXT NOT NULL,
	apparence TEXT NOT NULL,
	autres TEXT NOT NULL,
	cheveux CHARACTER VARYING(20) NOT NULL DEFAULT '',
	decalage INTEGER NOT NULL DEFAULT 0,
	deteste TEXT NOT NULL,
	lieu INTEGER NOT NULL DEFAULT 0,
	naissance BIGINT NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL DEFAULT 0,
	poids CHARACTER VARYING(20) NOT NULL DEFAULT '',
	taille CHARACTER VARYING(20) NOT NULL DEFAULT '',
	yeux CHARACTER VARYING(20) NOT NULL DEFAULT '',
		CONSTRAINT pk_details_perso PRIMARY KEY (perso)
);

CREATE TABLE dieux (
	bonus_comp CHARACTER VARYING(20) NOT NULL DEFAULT '',
	carte_mdm INT NULL,
	description TEXT NOT NULL,
	dossier INTEGER NOT NULL DEFAULT 0,
	ecole1 CHARACTER VARYING(20) NULL,
	ecole2 CHARACTER VARYING(20) NULL,
	ecole3 CHARACTER VARYING(20) NULL,
	effets TEXT NOT NULL,
	genre SMALLINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	image CHARACTER VARYING(15) NOT NULL DEFAULT '',
	missive_mdm SMALLINT NULL,
	nom CHARACTER VARYING(30) NOT NULL DEFAULT '',
	race CHARACTER VARYING(10) NOT NULL DEFAULT '',
	role CHARACTER VARYING(100) NOT NULL DEFAULT '',
		CONSTRAINT pk_dieux PRIMARY KEY (id)
);

CREATE TABLE discussions (
	auteur CHARACTER VARYING(40) NOT NULL DEFAULT '',
	crie SMALLINT NOT NULL DEFAULT 0,
	datetime INT NOT NULL DEFAULT 0,
	idfrom INTEGER NOT NULL DEFAULT 0,
	idto INTEGER NOT NULL DEFAULT 0,
	image_perso CHARACTER VARYING(128) NOT NULL DEFAULT '',
	langue CHARACTER VARYING(15) NOT NULL DEFAULT '',
	msg CHARACTER VARYING(255) NOT NULL DEFAULT '',
	x INT NOT NULL DEFAULT 0,
	y INT NOT NULL DEFAULT 0
);

CREATE TABLE dossiers (
	description CHARACTER VARYING(255) NOT NULL,
	id INTEGER NOT NULL,
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	params SMALLINT NOT NULL DEFAULT 0,
	parent INTEGER NOT NULL DEFAULT 0,
	type SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_dossiers PRIMARY KEY (id)
);

CREATE TABLE dossiers_missives (
	description CHARACTER VARYING(255) NOT NULL,
	id INTEGER NOT NULL,
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	params SMALLINT NOT NULL DEFAULT 0,
	parent INTEGER NOT NULL DEFAULT 0,
	type SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_dossiers_missives PRIMARY KEY (id)
);

CREATE TABLE droits (
	categorie CHARACTER VARYING(255) NOT NULL,
	description CHARACTER VARYING(255) NOT NULL,
	id INTEGER NOT NULL,
	nom CHARACTER VARYING(64) NOT NULL DEFAULT '',
	type CHARACTER VARYING(64) NOT NULL DEFAULT '',
	valeurs CHARACTER VARYING(255) NOT NULL,
		CONSTRAINT pk_droits PRIMARY KEY (id)
);

CREATE TABLE ecole_magie (
	couleur CHARACTER VARYING(20) NULL DEFAULT 'black',
	couleur2 CHARACTER VARYING(20) NULL DEFAULT 'black',
	couleur_bouton CHARACTER VARYING(20) NULL DEFAULT 'blanc',
	description TEXT NOT NULL,
	id INTEGER NOT NULL,
	nom CHARACTER VARYING(20) NOT NULL DEFAULT '',
		CONSTRAINT pk_ecole_magie PRIMARY KEY (id)
);

CREATE TABLE effet_sort (
	description TEXT NULL,
	fichier CHARACTER VARYING(30) NOT NULL DEFAULT '',
	id INTEGER NOT NULL,
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	nom_court CHARACTER VARYING(30) NOT NULL DEFAULT '',
		CONSTRAINT pk_effet_sort PRIMARY KEY (id)
);

CREATE TABLE effet_sort_assoc (
	effet_sort INTEGER NOT NULL DEFAULT 0,
	parametre TEXT NULL,
	type INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_effet_sort_assoc PRIMARY KEY (effet_sort,type)
);

CREATE TABLE effets (
	description TEXT NOT NULL,
	id INTEGER NOT NULL,
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	nom_court CHARACTER VARYING(30) NOT NULL DEFAULT '',
	params TEXT NOT NULL,
		CONSTRAINT pk_effets PRIMARY KEY (id)
);

CREATE TABLE evenement_relais (
	amplitudeDes INT NULL DEFAULT 0,
	amplitudeDesPrix INT NULL DEFAULT 0,
	choixPaye INT NULL DEFAULT 0,
	dateDebut CHARACTER VARYING(10) NULL,
	dateFin CHARACTER VARYING(10) NULL,
	desCreature INT NULL DEFAULT 0,
	description CHARACTER VARYING(255) NULL,
	desPrix INT NULL DEFAULT 0,
	fixeCreature INT NULL DEFAULT 0,
	fixePrix INT NULL DEFAULT 0,
	idCreature INT NULL,
	idEvenement INT NOT NULL,
	idVoyage INT NOT NULL,
	messageEvenement CHARACTER VARYING(255) NOT NULL DEFAULT 'Vous avez été attaqué sur le trajet ! Défendez-vous !',
	nombreRepetition INT NULL,
	pourcentage INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_evenement_relais PRIMARY KEY (idevenement)
);

CREATE TABLE evenements (
	auteur INTEGER NOT NULL DEFAULT 0,
	cible TEXT NOT NULL,
	date INT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	mj TEXT NOT NULL,
	neutre TEXT NOT NULL,
	soi TEXT NOT NULL,
	type SMALLINT NOT NULL DEFAULT 0,
	x INT NOT NULL DEFAULT 0,
	y INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_evenements PRIMARY KEY (id)
);

CREATE TABLE evenements_assoc (
	evenement BIGINT NOT NULL,
	localisable SMALLINT NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL,
	type SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_evenements_assoc PRIMARY KEY (evenement,perso,type)
);

CREATE TABLE familiers (
	description TEXT NOT NULL,
	id INTEGER NOT NULL,
	image CHARACTER VARYING(30) NOT NULL DEFAULT '',
	nom CHARACTER VARYING(30) NOT NULL DEFAULT '',
	sexe SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_familiers PRIMARY KEY (id)
);

CREATE TABLE faq (
	chapitre SMALLINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	question CHARACTER VARYING(255) NOT NULL DEFAULT '',
	reponse TEXT NOT NULL,
	schapitre SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_faq PRIMARY KEY (id)
);

CREATE TABLE forum_asso_msg (
	aut_sign CHARACTER VARYING(255) NOT NULL,
	auteur INTEGER NOT NULL DEFAULT 0,
	avatar CHARACTER VARYING(255) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	mj CHARACTER VARYING(40) NULL,
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume CHARACTER VARYING(64) NOT NULL DEFAULT '',
	sujet INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titres CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_asso_msg PRIMARY KEY (id)
);

CREATE TABLE forum_asso_sujets (
	auteur INTEGER NOT NULL DEFAULT 0,
	bloque SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	dernier_msg BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(200) NOT NULL DEFAULT '',
	forum INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	important SMALLINT NOT NULL DEFAULT 0,
	mj CHARACTER VARYING(40) NULL,
	nb_msg INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	start BIGINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_asso_sujets PRIMARY KEY (id)
);

CREATE TABLE forum_camp_msg (
	aut_sign CHARACTER VARYING(255) NOT NULL,
	auteur INTEGER NOT NULL DEFAULT 0,
	avatar CHARACTER VARYING(255) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	langues TEXT NOT NULL,
	mj CHARACTER VARYING(40) NULL,
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume CHARACTER VARYING(64) NOT NULL DEFAULT '',
	sujet INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titres CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_camp_msg PRIMARY KEY (id)
);

CREATE TABLE forum_camp_sujets (
	auteur INTEGER NOT NULL DEFAULT 0,
	bloque SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	dernier_msg BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(200) NOT NULL DEFAULT '',
	forum INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	important SMALLINT NOT NULL DEFAULT 0,
	mj CHARACTER VARYING(40) NULL,
	nb_msg INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume INTEGER NOT NULL DEFAULT 0,
	start BIGINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_camp_sujets PRIMARY KEY (id)
);

CREATE TABLE forum_contrees_msg (
	aut_sign CHARACTER VARYING(255) NOT NULL,
	auteur INTEGER NOT NULL DEFAULT 0,
	avatar CHARACTER VARYING(255) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	langues TEXT NOT NULL,
	mj CHARACTER VARYING(40) NULL,
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume CHARACTER VARYING(64) NOT NULL DEFAULT '',
	sujet INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titres CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_contrees_msg PRIMARY KEY (id)
);

CREATE TABLE forum_contrees_sujets (
	auteur INTEGER NOT NULL DEFAULT 0,
	bloque SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	dernier_msg BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(200) NOT NULL DEFAULT '',
	forum INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	important SMALLINT NOT NULL DEFAULT 0,
	mj CHARACTER VARYING(40) NULL,
	nb_msg INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	start BIGINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_contrees_sujets PRIMARY KEY (id)
);

CREATE TABLE forum_faq_msg (
	aut_sign CHARACTER VARYING(255) NOT NULL,
	auteur INTEGER NOT NULL DEFAULT 0,
	avatar CHARACTER VARYING(255) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	mj CHARACTER VARYING(40) NULL,
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume CHARACTER VARYING(64) NOT NULL DEFAULT '',
	sujet INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titres CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_faq_msg PRIMARY KEY (id)
);

CREATE TABLE forum_faq_sujets (
	auteur INTEGER NOT NULL DEFAULT 0,
	bloque SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	dernier_msg BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(200) NOT NULL DEFAULT '',
	forum INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	important SMALLINT NOT NULL DEFAULT 0,
	mj CHARACTER VARYING(40) NULL,
	nb_msg INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	start BIGINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_faq_sujets PRIMARY KEY (id)
);

CREATE TABLE forum_favoris (
	description CHARACTER VARYING(128) NOT NULL DEFAULT '',
	id_favori BIGINT NOT NULL,
	id_forum INTEGER NOT NULL DEFAULT 0,
	id_perso INTEGER NOT NULL DEFAULT 0,
	id_sujet INTEGER NOT NULL DEFAULT 0,
	id_ville INTEGER NULL,
	type_forum CHARACTER VARYING(15) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_favoris PRIMARY KEY (id_favori)
);

CREATE TABLE forum_hrp_msg (
	aut_sign CHARACTER VARYING(255) NOT NULL,
	auteur INTEGER NOT NULL DEFAULT 0,
	avatar CHARACTER VARYING(255) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	mj CHARACTER VARYING(40) NULL,
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume CHARACTER VARYING(64) NOT NULL DEFAULT '',
	sujet INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titres CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_hrp_msg PRIMARY KEY (id)
);

CREATE TABLE forum_hrp_sujets (
	auteur INTEGER NOT NULL DEFAULT 0,
	bloque SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	dernier_msg BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(200) NOT NULL DEFAULT '',
	forum INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	important SMALLINT NOT NULL DEFAULT 0,
	mj CHARACTER VARYING(40) NULL,
	nb_msg INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	start BIGINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_hrp_sujets PRIMARY KEY (id)
);

CREATE TABLE forum_liste (
	autorisations TEXT NOT NULL,
	BD SMALLINT NOT NULL DEFAULT 0,
	BG SMALLINT NOT NULL DEFAULT 0,
	date_limite BIGINT NOT NULL DEFAULT 0,
	der INTEGER NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	fond CHARACTER VARYING(40) NOT NULL DEFAULT '',
	forum CHARACTER VARYING(10) NOT NULL DEFAULT '',
	id INTEGER NOT NULL,
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	NV SMALLINT NOT NULL DEFAULT 0,
	ordre SMALLINT NOT NULL DEFAULT 0,
	param INTEGER NOT NULL DEFAULT 0,
	parent INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_liste PRIMARY KEY (id)
);

CREATE TABLE forum_mj_msg (
	aut_sign CHARACTER VARYING(255) NOT NULL,
	auteur INTEGER NOT NULL DEFAULT 0,
	avatar CHARACTER VARYING(255) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	mj INTEGER NOT NULL DEFAULT 0,
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume CHARACTER VARYING(64) NOT NULL DEFAULT '',
	sujet INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titres CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_mj_msg PRIMARY KEY (id)
);

CREATE TABLE forum_mj_sujets (
	auteur INTEGER NOT NULL DEFAULT 0,
	bloque SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	dernier_msg BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(200) NOT NULL DEFAULT '',
	forum INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	important SMALLINT NOT NULL DEFAULT 0,
	nb_msg INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	start BIGINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_mj_sujets PRIMARY KEY (id)
);

CREATE TABLE forum_reve_msg (
	aut_sign CHARACTER VARYING(255) NOT NULL,
	auteur INTEGER NOT NULL DEFAULT 0,
	avatar CHARACTER VARYING(255) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	langues TEXT NOT NULL,
	mj CHARACTER VARYING(40) NULL,
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume CHARACTER VARYING(64) NOT NULL DEFAULT '',
	sujet INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titres CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_reve_msg PRIMARY KEY (id)
);

CREATE TABLE forum_reve_sujets (
	auteur INTEGER NOT NULL DEFAULT 0,
	bloque SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	dernier_msg BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(200) NOT NULL DEFAULT '',
	forum INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	important SMALLINT NOT NULL DEFAULT 0,
	mj CHARACTER VARYING(40) NULL,
	nb_msg INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	start BIGINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_reve_sujets PRIMARY KEY (id)
);

CREATE TABLE forum_tech_msg (
	aut_sign CHARACTER VARYING(255) NOT NULL,
	auteur INTEGER NOT NULL DEFAULT 0,
	avatar CHARACTER VARYING(255) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	mj CHARACTER VARYING(40) NULL,
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume CHARACTER VARYING(64) NOT NULL DEFAULT '',
	sujet INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titres CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_tech_msg PRIMARY KEY (id)
);

CREATE TABLE forum_tech_sujets (
	auteur INTEGER NOT NULL DEFAULT 0,
	bloque SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	dernier_msg BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(200) NOT NULL DEFAULT '',
	forum INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	important SMALLINT NOT NULL DEFAULT 0,
	liste_status TEXT NOT NULL,
	mj CHARACTER VARYING(40) NULL,
	nb_msg INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	start BIGINT NOT NULL DEFAULT 0,
	type SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_tech_sujets PRIMARY KEY (id)
);

CREATE TABLE forum_ville_msg (
	aut_sign CHARACTER VARYING(255) NOT NULL,
	auteur INTEGER NOT NULL DEFAULT 0,
	avatar CHARACTER VARYING(255) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	langues TEXT NOT NULL,
	mj CHARACTER VARYING(40) NULL,
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	royaume CHARACTER VARYING(64) NOT NULL DEFAULT '',
	sujet INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titres CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_forum_ville_msg PRIMARY KEY (id)
);

CREATE TABLE forum_ville_sujets (
	auteur INTEGER NOT NULL DEFAULT 0,
	bloque SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	dernier_msg BIGINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(200) NOT NULL DEFAULT '',
	forum INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	important SMALLINT NOT NULL DEFAULT 0,
	mj CHARACTER VARYING(40) NULL,
	nb_msg INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom_auteur CHARACTER VARYING(64) NOT NULL DEFAULT '',
	start BIGINT NOT NULL DEFAULT 0,
	ville INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_forum_ville_sujets PRIMARY KEY (id)
);

CREATE TABLE goodies (
	coordonnees CHARACTER VARYING(255) NOT NULL,
	goodies CHARACTER VARYING(40) NOT NULL DEFAULT '',
	id BIGINT NOT NULL,
	login CHARACTER VARYING(50) NOT NULL DEFAULT '',
	paiement CHARACTER VARYING(40) NOT NULL DEFAULT '',
	param CHARACTER VARYING(20) NOT NULL DEFAULT '',
	port SMALLINT NOT NULL DEFAULT 0,
	prix INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_goodies PRIMARY KEY (id)
);

CREATE TABLE groupe_droit_assoc (
	droit INTEGER NOT NULL DEFAULT 0,
	groupe INTEGER NOT NULL DEFAULT 0,
	valeur CHARACTER VARYING(30) NULL,
		CONSTRAINT pk_groupe_droit_assoc PRIMARY KEY (droit,groupe)
);

CREATE TABLE habitations (
	coutAjoutCoffre INT NOT NULL DEFAULT 1000,
	coutAmeliorationHabitation INT NOT NULL DEFAULT 1000,
	description TEXT NOT NULL,
	idBatiment INT NOT NULL,
	idHabitation INT NOT NULL,
	imgHabitation CHARACTER VARYING(200) NOT NULL DEFAULT '',
	lienRP CHARACTER VARYING(200) NOT NULL DEFAULT '',
	nombreCoffreMax SMALLINT NOT NULL,
	nombrePlaceActuelle SMALLINT NOT NULL,
	nombrePlaceMax SMALLINT NOT NULL,
	nomHabitation CHARACTER VARYING(32) NOT NULL DEFAULT '',
		CONSTRAINT pk_habitations PRIMARY KEY (idhabitation)
);

CREATE TABLE ia (
	description CHARACTER VARYING(255) NOT NULL,
	fichier CHARACTER VARYING(30) NOT NULL,
	id BIGINT NOT NULL,
	nom CHARACTER VARYING(30) NOT NULL,
		CONSTRAINT pk_ia PRIMARY KEY (id)
);

CREATE TABLE images_equip (
	id BIGINT NOT NULL,
	image CHARACTER VARYING(30) NOT NULL DEFAULT '',
	race CHARACTER VARYING(10) NOT NULL DEFAULT '',
	sexe SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_images_equip PRIMARY KEY (id)
);

CREATE TABLE inscriptions (
	aime TEXT NOT NULL,
	alteration SMALLINT NOT NULL DEFAULT 0,
	annee INTEGER NOT NULL DEFAULT 0,
	apparence TEXT NOT NULL,
	autres TEXT NOT NULL,
	avatar CHARACTER VARYING(100) NOT NULL DEFAULT '',
	cheveux CHARACTER VARYING(20) NOT NULL DEFAULT '',
	competence CHARACTER VARYING(20) NOT NULL DEFAULT '',
	con SMALLINT NOT NULL DEFAULT 0,
	cycle INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	date_creation BIGINT NOT NULL DEFAULT 0,
	date_retour BIGINT NOT NULL DEFAULT 0,
	dc_raison TEXT NOT NULL,
	description CHARACTER VARYING(255) NOT NULL,
	destruction SMALLINT NOT NULL DEFAULT 0,
	deteste TEXT NOT NULL,
	dex SMALLINT NOT NULL DEFAULT 0,
	dieu INTEGER NOT NULL DEFAULT 0,
	double_compte SMALLINT NOT NULL DEFAULT 0,
	email CHARACTER VARYING(60) NOT NULL DEFAULT '',
	exp SMALLINT NOT NULL DEFAULT 0,
	force SMALLINT NOT NULL DEFAULT 0,
	id CHARACTER VARYING(32) NOT NULL DEFAULT '',
	intel SMALLINT NOT NULL DEFAULT 0,
	jour SMALLINT NOT NULL DEFAULT 0,
	justice SMALLINT NOT NULL DEFAULT 0,
	lieu INTEGER NOT NULL DEFAULT 0,
	login CHARACTER VARYING(40) NOT NULL DEFAULT '',
	mois SMALLINT NOT NULL DEFAULT 0,
	msg TEXT NOT NULL,
	negation SMALLINT NOT NULL DEFAULT 0,
	pass CHARACTER VARYING(30) NOT NULL DEFAULT '',
	per SMALLINT NOT NULL DEFAULT 0,
	poids CHARACTER VARYING(20) NOT NULL DEFAULT '',
	protection SMALLINT NOT NULL DEFAULT 0,
	race CHARACTER VARYING(10) NOT NULL DEFAULT '',
	retour SMALLINT NOT NULL DEFAULT 0,
	royaume INTEGER NOT NULL DEFAULT 0,
	sexe SMALLINT NOT NULL DEFAULT 0,
	taille CHARACTER VARYING(20) NOT NULL DEFAULT '',
	temple BIGINT NOT NULL DEFAULT 0,
	validation CHARACTER VARYING(32) NULL,
	vitalite SMALLINT NOT NULL DEFAULT 0,
	voie CHARACTER VARYING(20) NOT NULL DEFAULT '',
	yeux CHARACTER VARYING(20) NOT NULL DEFAULT '',
		CONSTRAINT pk_inscriptions PRIMARY KEY (id)
);

CREATE TABLE irl (
	cr INT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	id BIGINT NOT NULL,
	lieu CHARACTER VARYING(40) NOT NULL DEFAULT '',
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	organisation INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_irl PRIMARY KEY (id)
);

CREATE TABLE irl_participation (
	hebergement SMALLINT NOT NULL DEFAULT 0,
	irl BIGINT NOT NULL DEFAULT 0,
	locomotion SMALLINT NOT NULL DEFAULT 0,
	notes CHARACTER VARYING(255) NOT NULL,
	participation SMALLINT NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL DEFAULT 0,
	repas SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_irl_participation PRIMARY KEY (irl,perso)
);

CREATE TABLE logs (
	action CHARACTER VARYING(32) NOT NULL DEFAULT '0',
	auteur INTEGER NOT NULL DEFAULT 0,
	ip CHARACTER VARYING(15) NULL,
	params TEXT NOT NULL,
	time TIMESTAMP NOT NULL,
	type CHARACTER VARYING(40) NOT NULL DEFAULT ''
);

CREATE TABLE logs_dev (
	action TEXT NOT NULL,
	cible INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	nom_aut CHARACTER VARYING(40) NOT NULL DEFAULT '',
	nom_dest CHARACTER VARYING(40) NOT NULL DEFAULT '',
	perso INTEGER NOT NULL DEFAULT 0,
	type SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_logs_dev PRIMARY KEY (id)
);

CREATE TABLE logs_mj (
	action TEXT NOT NULL,
	cible INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	nom_aut CHARACTER VARYING(40) NOT NULL DEFAULT '',
	nom_dest CHARACTER VARYING(40) NOT NULL DEFAULT '',
	perso INTEGER NOT NULL DEFAULT 0,
	type SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_logs_mj PRIMARY KEY (id)
);

CREATE TABLE membres (
	adherent BIGINT NOT NULL DEFAULT 0,
	autorise SMALLINT NOT NULL DEFAULT 1,
	avatar CHARACTER VARYING(255) NULL,
	avatar_mj CHARACTER VARYING(64) NOT NULL,
	bonus_xp INT NOT NULL DEFAULT 0,
	bypass_auto_delete SMALLINT NOT NULL DEFAULT 0,
	charte SMALLINT NOT NULL DEFAULT 0,
	cree BIGINT NOT NULL DEFAULT 0,
	dernier_acces BIGINT NOT NULL DEFAULT 0,
	descr_pnj CHARACTER VARYING(255) NOT NULL,
	description TEXT NOT NULL,
	dieu INTEGER NOT NULL DEFAULT 0,
	ecole1 CHARACTER VARYING(20) NOT NULL DEFAULT '',
	ecole2 CHARACTER VARYING(20) NOT NULL DEFAULT '',
	ecole3 CHARACTER VARYING(20) NOT NULL DEFAULT '',
	email CHARACTER VARYING(60) NOT NULL DEFAULT '',
	event INT NOT NULL DEFAULT 0,
	familier INTEGER NULL,
	garde_equipement SMALLINT NOT NULL DEFAULT 0,
	grade_site SMALLINT NOT NULL DEFAULT 0,
	groupe INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	id_joue INTEGER NULL,
	id_mj INTEGER NULL,
	id_pj INTEGER NULL,
	interface_mj SMALLINT NOT NULL DEFAULT 0,
	mort_absolue SMALLINT NOT NULL DEFAULT 0,
	motif_mortabs SMALLINT NOT NULL DEFAULT 0,
	nb_xp_bonus INT NOT NULL DEFAULT 0,
	niveauRP REAL NOT NULL DEFAULT 65535,
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	nom_familier CHARACTER VARYING(30) NOT NULL DEFAULT '',
	pass CHARACTER VARYING(32) NOT NULL DEFAULT '',
	race CHARACTER VARYING(10) NOT NULL DEFAULT '',
	rep_ressources CHARACTER VARYING(255) NULL,
	representant INTEGER NOT NULL DEFAULT 0,
	royaume INTEGER NOT NULL DEFAULT 0,
	sexe SMALLINT NOT NULL DEFAULT 0,
	specialite CHARACTER VARYING(50) NULL,
	titre INTEGER NOT NULL DEFAULT 0,
	vacances BIGINT NULL,
	validation INTEGER NOT NULL DEFAULT 0,
	voie CHARACTER VARYING(10) NOT NULL DEFAULT '',
	zombie SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_membres PRIMARY KEY (id)
);

CREATE TABLE missives (
	archiver_from SMALLINT NOT NULL DEFAULT 0,
	archiver_to SMALLINT NOT NULL DEFAULT 0,
	cacher SMALLINT NOT NULL DEFAULT 0,
	cacher_dest SMALLINT NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	destinataires TEXT NULL,
	dossier INTEGER NULL,
	dossier_envoi INTEGER NULL,
	id BIGINT NOT NULL,
	idfrom INTEGER NOT NULL DEFAULT 0,
	idto INTEGER NOT NULL DEFAULT 0,
	langues TEXT NOT NULL,
	lue BIGINT NOT NULL DEFAULT 0,
	mjfrom SMALLINT NOT NULL DEFAULT 0,
	mjto SMALLINT NOT NULL DEFAULT 0,
	nomfrom CHARACTER VARYING(40) NOT NULL,
	nomto CHARACTER VARYING(40) NOT NULL,
	sujet CHARACTER VARYING(80) NOT NULL DEFAULT '',
	supprimer SMALLINT NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
		CONSTRAINT pk_missives PRIMARY KEY (id)
);

CREATE TABLE modeles_missive (
	auteur INTEGER NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	sujet CHARACTER VARYING(80) NOT NULL DEFAULT '',
	texte TEXT NOT NULL,
		CONSTRAINT pk_modeles_missive PRIMARY KEY (id)
);

CREATE TABLE morts (
	auteur CHARACTER VARYING(100) NOT NULL DEFAULT '',
	cible CHARACTER VARYING(100) NOT NULL DEFAULT '',
	date BIGINT NOT NULL DEFAULT 0,
	idfrom INTEGER NOT NULL DEFAULT 0,
	idto INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE news (
	auteur INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	nom_auteur CHARACTER VARYING(40) NOT NULL DEFAULT '',
	royaume INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titre CHARACTER VARYING(50) NOT NULL DEFAULT '',
	type CHARACTER VARYING(3) NOT NULL DEFAULT '',
		CONSTRAINT pk_news PRIMARY KEY (id)
);

CREATE TABLE notes (
	contenu CHARACTER VARYING(255) NOT NULL,
	date BIGINT NOT NULL DEFAULT 0,
	idMj INTEGER NOT NULL DEFAULT 0,
	idNote INTEGER NOT NULL,
	idPerso INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_notes PRIMARY KEY (idnote)
);

CREATE TABLE notes_chroniques (
	auteur INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	id INT NOT NULL,
	nom_auteur CHARACTER VARYING(40) NOT NULL,
	perso INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
		CONSTRAINT pk_notes_chroniques PRIMARY KEY (id)
);

CREATE TABLE notes_collections (
	id INTEGER NOT NULL,
	nom CHARACTER VARYING(50) NOT NULL DEFAULT '',
	perso INTEGER NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
		CONSTRAINT pk_notes_collections PRIMARY KEY (id,perso)
);

CREATE TABLE objets (
	afficher SMALLINT NOT NULL DEFAULT 0,
	artefact SMALLINT NOT NULL DEFAULT 0,
	competence_min CHARACTER VARYING(255) NULL,
	description TEXT NOT NULL,
	dossier INTEGER NOT NULL DEFAULT 0,
	effets TEXT NOT NULL,
	enchantable SMALLINT NOT NULL,
	enco INTEGER NOT NULL DEFAULT 0,
	fichier CHARACTER VARYING(40) NOT NULL DEFAULT '',
	genre SMALLINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	image CHARACTER VARYING(50) NOT NULL DEFAULT '',
	location TEXT NULL,
	maudit SMALLINT NOT NULL DEFAULT 0,
	niveau SMALLINT NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(40) NOT NULL,
	nom_util CHARACTER VARYING(30) NOT NULL DEFAULT '',
	nombre SMALLINT NOT NULL DEFAULT 1,
	pack SMALLINT NOT NULL DEFAULT 0,
	param CHARACTER VARYING(10) NULL,
	poids INTEGER NOT NULL DEFAULT 0,
	portable SMALLINT NOT NULL DEFAULT 0,
	prix INTEGER NOT NULL DEFAULT 0,
	race CHARACTER VARYING(10) NOT NULL DEFAULT '',
	sol INTEGER NOT NULL DEFAULT 0,
	type CHARACTER VARYING(10) NOT NULL DEFAULT '',
	vendeur CHARACTER VARYING(20) NOT NULL DEFAULT '',
		CONSTRAINT pk_objets PRIMARY KEY (id)
);

CREATE TABLE objets_terre (
	equipement TEXT NOT NULL,
	x INT NOT NULL DEFAULT 0,
	y INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_objets_terre PRIMARY KEY (x,y)
);

CREATE TABLE options_serveur (
	id BIGINT NOT NULL,
	nom CHARACTER VARYING(255) NOT NULL DEFAULT '',
	valeur CHARACTER VARYING(255) NOT NULL DEFAULT '',
		CONSTRAINT pk_options_serveur PRIMARY KEY (id)
);

CREATE TABLE parametrage (
	idParametrage INT NOT NULL,
	libelle CHARACTER VARYING(32) NOT NULL,
	modifiable CHARACTER VARYING(3) NOT NULL DEFAULT 'non',
	typeParametre CHARACTER VARYING(32) NULL,
	valeur CHARACTER VARYING(11) NOT NULL DEFAULT '0',
		CONSTRAINT pk_parametrage PRIMARY KEY (idparametrage)
);

CREATE TABLE parures (
	afficher SMALLINT NOT NULL DEFAULT 1,
	artefact SMALLINT NOT NULL DEFAULT 0,
	classe SMALLINT NOT NULL DEFAULT 0,
	competence_min CHARACTER VARYING(255) NULL,
	description TEXT NOT NULL,
	dossier INTEGER NOT NULL DEFAULT 0,
	effets TEXT NOT NULL,
	enchantable SMALLINT NOT NULL,
	enco INTEGER NOT NULL DEFAULT 0,
	force INTEGER NOT NULL DEFAULT 0,
	genre SMALLINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	image CHARACTER VARYING(50) NOT NULL,
	location TEXT NULL,
	maudit SMALLINT NOT NULL DEFAULT 0,
	niveau SMALLINT NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	nom2 CHARACTER VARYING(20) NOT NULL DEFAULT '',
	poids INTEGER NOT NULL DEFAULT 0,
	prix INTEGER NOT NULL DEFAULT 0,
	race CHARACTER VARYING(10) NOT NULL DEFAULT '',
	sol INTEGER NOT NULL DEFAULT 0,
	sorts_aut SMALLINT NOT NULL DEFAULT 0,
	type CHARACTER VARYING(10) NOT NULL DEFAULT '',
	vendeur CHARACTER VARYING(20) NOT NULL DEFAULT '',
		CONSTRAINT pk_parures PRIMARY KEY (id)
);

CREATE TABLE pioms_perso (
	perso INTEGER NOT NULL,
	po INT NOT NULL DEFAULT 0,
	v_achetes TEXT NOT NULL,
	v_portes TEXT NOT NULL,
		CONSTRAINT pk_pioms_perso PRIMARY KEY (perso)
);

CREATE TABLE preferences (
	avert_missive SMALLINT NOT NULL DEFAULT 0,
	avert_missive_attaque SMALLINT NOT NULL DEFAULT 0,
	bouton_tir SMALLINT NOT NULL DEFAULT 1,
	cacher_menu SMALLINT NOT NULL DEFAULT 0,
	compact_forum SMALLINT NOT NULL DEFAULT 0,
	equipement SMALLINT NOT NULL DEFAULT 1,
	forum_plein_ecran SMALLINT NOT NULL DEFAULT 0,
	gd_ecran SMALLINT NOT NULL DEFAULT 0,
	grille SMALLINT NOT NULL DEFAULT 0,
	image_equip CHARACTER VARYING(32) NOT NULL DEFAULT '',
	montrer_email SMALLINT NOT NULL DEFAULT 0,
	msg_jour SMALLINT NOT NULL DEFAULT 0,
	nb_msg_page SMALLINT NOT NULL DEFAULT 0,
	nb_sujets_page SMALLINT NOT NULL DEFAULT 0,
	newsletter SMALLINT NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL,
	plein_ecran SMALLINT NOT NULL DEFAULT 0,
	polices SMALLINT NOT NULL DEFAULT 0,
	reduire SMALLINT NOT NULL DEFAULT 0,
	signature CHARACTER VARYING(255) NOT NULL,
	signature_missives CHARACTER VARYING(255) NOT NULL,
	signature_mj CHARACTER VARYING(255) NOT NULL,
	skin SMALLINT NOT NULL DEFAULT 0,
	son SMALLINT NOT NULL DEFAULT 0,
	style CHARACTER VARYING(20) NOT NULL DEFAULT '',
		CONSTRAINT pk_preferences PRIMARY KEY (perso)
);

CREATE TABLE profil (
	attitude SMALLINT NOT NULL DEFAULT 0,
	balance_atk SMALLINT NOT NULL DEFAULT 0,
	batiment INT NOT NULL DEFAULT 0,
	camoufle SMALLINT NOT NULL DEFAULT 0,
	ci SMALLINT NOT NULL DEFAULT 0,
	con INTEGER NOT NULL DEFAULT 0,
	concentre SMALLINT NOT NULL DEFAULT 0,
	date_dernier_regain BIGINT NOT NULL DEFAULT 0,
	date_salaire BIGINT NOT NULL DEFAULT 0,
	dex INTEGER NOT NULL DEFAULT 0,
	equipement TEXT NOT NULL,
	esquive SMALLINT NOT NULL DEFAULT 0,
	evenements TEXT NOT NULL,
	exp INTEGER NOT NULL DEFAULT 0,
	fatigue SMALLINT NOT NULL DEFAULT 0,
	force INTEGER NOT NULL DEFAULT 0,
	gold INT NOT NULL DEFAULT 0,
	image CHARACTER VARYING(50) NULL,
	infos_tour CHARACTER VARYING(255) NULL,
	intel INTEGER NOT NULL DEFAULT 0,
	livre_recettes TEXT NULL,
	livre_recoltes TEXT NULL,
	livre_sorts TEXT NOT NULL,
	mana REAL NOT NULL DEFAULT 0,
	mort SMALLINT NOT NULL DEFAULT 0,
	niveau BIGINT NOT NULL DEFAULT 1,
	nouv_missive SMALLINT NOT NULL DEFAULT 0,
	nouv_missive_mj SMALLINT NOT NULL DEFAULT 0,
	or_ca INT NOT NULL DEFAULT 0,
	or_hb INT NOT NULL DEFAULT 0,
	or_ithoria INT NOT NULL DEFAULT 0,
	or_kohr INT NOT NULL DEFAULT 0,
	or_pe INT NOT NULL DEFAULT 0,
	orientation CHARACTER(2) NOT NULL DEFAULT '',
	pa REAL NOT NULL DEFAULT 0,
	parole REAL NOT NULL DEFAULT 0,
	per INTEGER NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL,
	pm REAL NOT NULL DEFAULT 0,
	prochain_tour BIGINT NULL,
	pts_perso SMALLINT NOT NULL DEFAULT 0,
	pv REAL NOT NULL DEFAULT 0,
	relations TEXT NOT NULL,
	session CHARACTER VARYING(32) NULL,
	sorts TEXT NULL,
	x INT NULL,
	xp BIGINT NOT NULL DEFAULT 0,
	y INT NULL,
		CONSTRAINT pk_profil PRIMARY KEY (perso)
);

CREATE TABLE profil_bisar (
	attitude SMALLINT NOT NULL DEFAULT 0,
	balance_atk SMALLINT NOT NULL DEFAULT 0,
	batiment INT NOT NULL DEFAULT 0,
	camoufle SMALLINT NOT NULL DEFAULT 0,
	ci SMALLINT NOT NULL DEFAULT 0,
	con INTEGER NOT NULL DEFAULT 0,
	concentre SMALLINT NOT NULL DEFAULT 0,
	date_dernier_regain BIGINT NOT NULL DEFAULT 0,
	date_salaire BIGINT NOT NULL DEFAULT 0,
	dex INTEGER NOT NULL DEFAULT 0,
	equipement TEXT NOT NULL,
	esquive SMALLINT NOT NULL DEFAULT 0,
	evenements TEXT NOT NULL,
	exp INTEGER NOT NULL DEFAULT 0,
	fatigue SMALLINT NOT NULL DEFAULT 0,
	force INTEGER NOT NULL DEFAULT 0,
	gold INT NOT NULL DEFAULT 0,
	image CHARACTER VARYING(50) NULL,
	infos_tour CHARACTER VARYING(255) NULL,
	intel INTEGER NOT NULL DEFAULT 0,
	livre_recettes TEXT NULL,
	livre_recoltes TEXT NULL,
	livre_sorts TEXT NOT NULL,
	mana REAL NOT NULL DEFAULT 0,
	mort SMALLINT NOT NULL DEFAULT 0,
	niveau BIGINT NOT NULL DEFAULT 1,
	nouv_missive SMALLINT NOT NULL DEFAULT 0,
	nouv_missive_mj SMALLINT NOT NULL DEFAULT 0,
	or_ca INTEGER NOT NULL DEFAULT 0,
	or_hb INTEGER NOT NULL DEFAULT 0,
	or_ithoria INTEGER NOT NULL DEFAULT 0,
	or_kohr INTEGER NOT NULL DEFAULT 0,
	or_pe INTEGER NOT NULL DEFAULT 0,
	orientation CHARACTER(2) NOT NULL DEFAULT '',
	pa REAL NOT NULL DEFAULT 0,
	parole REAL NOT NULL DEFAULT 0,
	per INTEGER NOT NULL DEFAULT 0,
	perso INTEGER NOT NULL,
	pm REAL NOT NULL DEFAULT 0,
	prochain_tour BIGINT NULL,
	pts_perso SMALLINT NOT NULL DEFAULT 0,
	pv REAL NOT NULL DEFAULT 0,
	relations TEXT NOT NULL,
	session CHARACTER VARYING(32) NULL,
	sorts TEXT NULL,
	x INT NULL,
	xp BIGINT NOT NULL DEFAULT 0,
	y INT NULL,
		CONSTRAINT pk_profil_bisar PRIMARY KEY (perso)
);

CREATE TABLE profil_forum (
	date_asso TEXT NOT NULL,
	date_camp TEXT NOT NULL,
	date_contrees TEXT NOT NULL,
	date_faq TEXT NOT NULL,
	date_hrp TEXT NOT NULL,
	date_mj TEXT NOT NULL,
	date_reve TEXT NOT NULL,
	date_tech TEXT NOT NULL,
	date_ville TEXT NOT NULL,
	lus_asso TEXT NOT NULL,
	lus_camp TEXT NOT NULL,
	lus_contrees TEXT NOT NULL,
	lus_faq TEXT NOT NULL,
	lus_hrp TEXT NOT NULL,
	lus_mj TEXT NOT NULL,
	lus_reve TEXT NOT NULL,
	lus_tech TEXT NOT NULL,
	lus_ville TEXT NOT NULL,
	perso INTEGER NOT NULL,
		CONSTRAINT pk_profil_forum PRIMARY KEY (perso)
);

CREATE TABLE promotions (
	auteur INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	motif CHARACTER VARYING(255) NOT NULL,
	nom_auteur CHARACTER VARYING(40) NOT NULL,
	perso INTEGER NOT NULL DEFAULT 0,
	sujet CHARACTER VARYING(255) NOT NULL,
		CONSTRAINT pk_promotions PRIMARY KEY (id)
);

CREATE TABLE question_sub (
	perso INTEGER NOT NULL DEFAULT 0,
	reponse CHARACTER VARYING(255) NOT NULL,
		CONSTRAINT pk_question_sub PRIMARY KEY (perso)
);

CREATE TABLE questionnaire_q (
	explication TEXT NOT NULL,
	id SMALLINT NOT NULL,
	indice CHARACTER VARYING(64) NULL DEFAULT 'Ce que vous devez savoir de l''univers d''Ideo',
	royaume SMALLINT NOT NULL DEFAULT -1,
	texte CHARACTER VARYING(255) NOT NULL,
		CONSTRAINT pk_questionnaire_q PRIMARY KEY (id)
);

CREATE TABLE questionnaire_r (
	bonne SMALLINT NOT NULL DEFAULT 0,
	id SMALLINT NOT NULL,
	question SMALLINT NOT NULL DEFAULT 0,
	texte CHARACTER VARYING(255) NOT NULL,
		CONSTRAINT pk_questionnaire_r PRIMARY KEY (id)
);

CREATE TABLE recettes (
	artisanat CHARACTER VARYING(20) NOT NULL DEFAULT '',
	carac CHARACTER VARYING(10) NOT NULL DEFAULT '',
	classe CHARACTER VARYING(20) NOT NULL DEFAULT '',
	competence CHARACTER VARYING(30) NOT NULL DEFAULT '',
	competence_pourcentage SMALLINT NULL,
	dossier INTEGER NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	id_objet INTEGER NOT NULL DEFAULT 0,
	ingredients CHARACTER VARYING(255) NOT NULL,
	location CHARACTER VARYING(128) NOT NULL DEFAULT '',
	niveau SMALLINT NOT NULL DEFAULT 0,
	nombre SMALLINT NOT NULL DEFAULT 0,
	outils CHARACTER VARYING(255) NOT NULL,
	prix SMALLINT NOT NULL DEFAULT 0,
	race CHARACTER VARYING(10) NOT NULL DEFAULT '',
	trouvable SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_recettes PRIMARY KEY (id)
);

CREATE TABLE relais (
	idBatiment INT NOT NULL,
	idRelais INT NOT NULL,
	idRoyaume INT NULL,
	idVille INT NULL,
	imgRelais CHARACTER VARYING(255) NULL,
	messageAccueil CHARACTER VARYING(255) NOT NULL DEFAULT 'Bienvenue !',
	nomRelais CHARACTER VARYING(32) NOT NULL DEFAULT 'Relais',
	tresorerie INT NULL DEFAULT 0,
		CONSTRAINT pk_relais PRIMARY KEY (idrelais)
);

CREATE TABLE relations (
	a SMALLINT NOT NULL DEFAULT 0,
	de SMALLINT NOT NULL DEFAULT 0,
	smiley CHARACTER VARYING(10) NOT NULL DEFAULT '',
	type TEXT NOT NULL,
		CONSTRAINT pk_relations PRIMARY KEY (a,de)
);

CREATE TABLE repertoire (
	bloques TEXT NOT NULL,
	commentaires TEXT NOT NULL,
	contacts TEXT NOT NULL,
	perso INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_repertoire PRIMARY KEY (perso)
);

CREATE TABLE royaumes (
	auteur_missive INTEGER NOT NULL DEFAULT 0,
	couleur CHARACTER VARYING(6) NOT NULL DEFAULT '',
	description TEXT NOT NULL,
	elfe SMALLINT NOT NULL DEFAULT 0,
	forum CHARACTER VARYING(30) NULL,
	genre SMALLINT NOT NULL DEFAULT 0,
	humain SMALLINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	missive_accueil TEXT NOT NULL,
	monnaie CHARACTER VARYING(10) NOT NULL DEFAULT '',
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	orc SMALLINT NOT NULL DEFAULT 0,
	race CHARACTER VARYING(10) NOT NULL DEFAULT '',
	type_img CHARACTER VARYING(15) NOT NULL DEFAULT '',
		CONSTRAINT pk_royaumes PRIMARY KEY (id)
);

CREATE TABLE save_jet (
	action CHARACTER VARYING(255) NOT NULL,
	bonus INT NOT NULL,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	de INT NOT NULL,
	faces INT NOT NULL,
	id INT NOT NULL,
	id_membre INT NOT NULL,
	resultat INT NOT NULL,
		CONSTRAINT pk_save_jet PRIMARY KEY (id)
);

CREATE TABLE skins (
	acces_pj SMALLINT NOT NULL DEFAULT 0,
	CSS SMALLINT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(255) NOT NULL,
	dossier CHARACTER VARYING(32) NOT NULL DEFAULT '',
	id INT NOT NULL,
	nom CHARACTER VARYING(32) NOT NULL DEFAULT '',
	params CHARACTER VARYING(255) NOT NULL,
		CONSTRAINT pk_skins PRIMARY KEY (id)
);

CREATE TABLE sort (
	acces INT NOT NULL DEFAULT 0,
	cout_mana INT NULL,
	description TEXT NOT NULL,
	dieux CHARACTER VARYING(64) NOT NULL DEFAULT '',
	difficulte INT NOT NULL DEFAULT 0,
	ecole CHARACTER VARYING(20) NOT NULL DEFAULT 'aucune',
	fichier CHARACTER VARYING(20) NOT NULL DEFAULT '',
	hit_and_run SMALLINT NOT NULL DEFAULT 0,
	id INTEGER NOT NULL,
	image CHARACTER VARYING(64) NULL,
	image_bouton CHARACTER VARYING(64) NULL,
	js SMALLINT NOT NULL DEFAULT 0,
	niveau INT NOT NULL DEFAULT 1,
	nom CHARACTER VARYING(35) NOT NULL DEFAULT '',
	nom_court CHARACTER VARYING(20) NOT NULL DEFAULT '',
	pnj SMALLINT NOT NULL DEFAULT 0,
	portee INT NOT NULL DEFAULT 0,
	soi SMALLINT NOT NULL DEFAULT 1,
	voie CHARACTER VARYING(64) NOT NULL DEFAULT '',
		CONSTRAINT pk_sort PRIMARY KEY (id)
);

CREATE TABLE sort_assoc (
	parametre TEXT NULL,
	sort INTEGER NOT NULL DEFAULT 0,
	type INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_sort_assoc PRIMARY KEY (sort,type)
);

CREATE TABLE templates_batiment (
	description TEXT NOT NULL,
	hauteur SMALLINT NOT NULL DEFAULT 1,
	id BIGINT NOT NULL,
	image CHARACTER VARYING(50) NOT NULL DEFAULT '',
	largeur SMALLINT NOT NULL DEFAULT 1,
	limite_action BIGINT NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(45) NOT NULL DEFAULT '',
	objectif CHARACTER VARYING(128) NOT NULL DEFAULT '',
	param BIGINT NOT NULL DEFAULT 0,
	type INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_templates_batiment PRIMARY KEY (id)
);

CREATE TABLE terrains (
	acces SMALLINT NOT NULL DEFAULT 0,
	bloc SMALLINT NOT NULL DEFAULT 0,
	bonus_atk SMALLINT NOT NULL DEFAULT 0,
	bonus_def SMALLINT NOT NULL DEFAULT 0,
	bonus_vis SMALLINT NOT NULL DEFAULT 0,
	couleur CHARACTER VARYING(6) NOT NULL DEFAULT '',
	cout_dep SMALLINT NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	fichier CHARACTER VARYING(64) NOT NULL DEFAULT '',
	filtres CHARACTER VARYING(255) NOT NULL,
	genre SMALLINT NOT NULL DEFAULT 0,
	id BIGINT NOT NULL,
	liste_recolte TEXT NULL,
	nbimages CHARACTER VARYING(64) NOT NULL DEFAULT '100',
	nom CHARACTER VARYING(42) NOT NULL DEFAULT '',
	parent BIGINT NOT NULL DEFAULT 0,
	regen SMALLINT NOT NULL DEFAULT 0,
	regen_equip SMALLINT NOT NULL DEFAULT 0,
	script CHARACTER VARYING(64) NOT NULL DEFAULT '',
	type INTEGER NOT NULL DEFAULT 0,
	z_index SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_terrains PRIMARY KEY (id)
);

CREATE TABLE tickets_surf (
	date_transaction TIMESTAMP NOT NULL,
	id_transaction BIGINT NOT NULL,
	result SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_tickets_surf PRIMARY KEY (id_transaction)
);

CREATE TABLE titres (
	budget INT NULL,
	compte INT NULL,
	description TEXT NOT NULL,
	id INTEGER NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(50) NOT NULL DEFAULT '',
	nom_fem CHARACTER VARYING(50) NULL,
	parent INTEGER NOT NULL DEFAULT 0,
	revenu INT NULL,
	royaume INTEGER NOT NULL DEFAULT 0,
	visible SMALLINT NULL DEFAULT 1,
		CONSTRAINT pk_titres PRIMARY KEY (id,royaume)
);

CREATE TABLE titres_joueurs (
	perso INTEGER NOT NULL DEFAULT 0,
	royaume INTEGER NOT NULL DEFAULT 0,
	titre INTEGER NOT NULL DEFAULT 0,
		CONSTRAINT pk_titres_joueurs PRIMARY KEY (perso,royaume,titre)
);

CREATE TABLE trajets (
	idTrajet INT NOT NULL,
	idVoyage INT NOT NULL,
	position INT NOT NULL,
	x_arrive INT NOT NULL,
	x_depart INT NOT NULL,
	y_arrive INT NOT NULL,
	y_depart INT NOT NULL,
		CONSTRAINT pk_trajets PRIMARY KEY (idtrajet)
);

CREATE TABLE transferts (
	auteur INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL DEFAULT 0,
	id INT NOT NULL,
	idfrom INT NOT NULL DEFAULT 0,
	idto INT NOT NULL DEFAULT 0,
	montant INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_transferts PRIMARY KEY (id)
);

CREATE TABLE types_creatures (
	afficher SMALLINT NOT NULL DEFAULT 1,
	armure SMALLINT NOT NULL DEFAULT 0,
	bonus SMALLINT NOT NULL DEFAULT 0,
	camoufle SMALLINT NOT NULL DEFAULT 0,
	de SMALLINT NOT NULL DEFAULT 0,
	degats SMALLINT NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	dossier INTEGER NOT NULL DEFAULT 0,
	ecole CHARACTER VARYING(20) NOT NULL DEFAULT '',
	effets TEXT NOT NULL,
	effets_attaque TEXT NOT NULL,
	esquive SMALLINT NOT NULL DEFAULT 0,
	familles CHARACTER VARYING(50) NOT NULL DEFAULT '',
	fichier_blessures CHARACTER VARYING(40) NOT NULL DEFAULT '',
	fichier_degats CHARACTER VARYING(40) NOT NULL DEFAULT '',
	gains TEXT NULL,
	genre SMALLINT NOT NULL DEFAULT 0,
	hauteur SMALLINT NOT NULL DEFAULT 1,
	id BIGINT NOT NULL,
	image CHARACTER VARYING(50) NOT NULL,
	intel SMALLINT NOT NULL DEFAULT 0,
	largeur SMALLINT NOT NULL DEFAULT 1,
	milieux TEXT NULL,
	niveau SMALLINT NOT NULL DEFAULT 1,
	nom CHARACTER VARYING(40) NOT NULL,
	pm SMALLINT NOT NULL DEFAULT 0,
	pnj SMALLINT NOT NULL DEFAULT 0,
	portee SMALLINT NOT NULL DEFAULT 1,
	precis SMALLINT NOT NULL DEFAULT 0,
	pv SMALLINT NOT NULL DEFAULT 0,
	regen SMALLINT NOT NULL DEFAULT 1,
	resist_magie SMALLINT NOT NULL DEFAULT 0,
	volonte SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_types_creatures PRIMARY KEY (id)
);

CREATE TABLE updates (
	date BIGINT NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	id INT NOT NULL,
	type SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_updates PRIMARY KEY (id)
);

CREATE TABLE user_groups (
	attributs TEXT NOT NULL,
	id INTEGER NOT NULL,
	niveau BIGINT NOT NULL DEFAULT 0,
	nom CHARACTER VARYING(64) NOT NULL DEFAULT '',
		CONSTRAINT pk_user_groups PRIMARY KEY (id)
);

CREATE TABLE vehicules (
	description CHARACTER VARYING(255) NULL,
	idVehicule INT NOT NULL,
	modifCout INT NULL DEFAULT 0,
	modifDureeHeure INT NULL DEFAULT 0,
	modifPA INT NULL DEFAULT 0,
	modifPM INT NULL DEFAULT 0,
	modifRisque INT NULL DEFAULT 0,
	nbPlaceMax INT NULL DEFAULT 1,
	nom CHARACTER VARYING(50) NOT NULL,
		CONSTRAINT pk_vehicules PRIMARY KEY (idvehicule)
);

CREATE TABLE vetements_piom (
	auteur CHARACTER VARYING(40) NULL DEFAULT '',
	description CHARACTER VARYING(255) NULL,
	ensemble CHARACTER VARYING(30) NOT NULL DEFAULT '',
	id INTEGER NOT NULL,
	image CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom CHARACTER VARYING(30) NOT NULL DEFAULT '',
	piom INT NOT NULL DEFAULT 0,
	prix SMALLINT NOT NULL DEFAULT 0,
	rarete SMALLINT NOT NULL DEFAULT 0,
	type CHARACTER VARYING(30) NOT NULL DEFAULT '',
	vendable SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_vetements_piom PRIMARY KEY (id)
);

CREATE TABLE vetements_piom2 (
	auteur CHARACTER VARYING(40) NULL DEFAULT '',
	description CHARACTER VARYING(255) NULL,
	ensemble CHARACTER VARYING(30) NOT NULL DEFAULT '',
	id INTEGER NOT NULL,
	image CHARACTER VARYING(100) NOT NULL DEFAULT '',
	nom CHARACTER VARYING(30) NOT NULL DEFAULT '',
	piom INT NOT NULL DEFAULT 0,
	prix SMALLINT NOT NULL DEFAULT 0,
	rarete SMALLINT NOT NULL DEFAULT 0,
	type CHARACTER VARYING(30) NOT NULL DEFAULT '',
	vendable SMALLINT NOT NULL DEFAULT 0,
		CONSTRAINT pk_vetements_piom2 PRIMARY KEY (id)
);

CREATE TABLE villes (
	birthplace SMALLINT NOT NULL DEFAULT 1,
	camp_origine INTEGER NOT NULL DEFAULT 0,
	description TEXT NOT NULL,
	gains INT NULL,
	id INTEGER NOT NULL,
	image CHARACTER VARYING(20) NOT NULL DEFAULT '',
	maire INTEGER NOT NULL DEFAULT 0,
	monnaies CHARACTER VARYING(100) NOT NULL DEFAULT '',
	msg_bienvenue CHARACTER VARYING(255) NOT NULL,
	nom CHARACTER VARYING(40) NOT NULL DEFAULT '',
	permissions CHARACTER VARYING(255) NOT NULL DEFAULT '',
	ratio_carte SMALLINT NOT NULL DEFAULT 10,
	showinfos SMALLINT NULL DEFAULT 1,
	terrains TEXT NOT NULL,
	x1 INT NOT NULL DEFAULT 0,
	x2 INT NOT NULL DEFAULT 0,
	x_carte INT NOT NULL DEFAULT 0,
	y1 INT NOT NULL DEFAULT 0,
	y2 INT NOT NULL DEFAULT 0,
	y_carte INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_villes PRIMARY KEY (id)
);

CREATE TABLE voyages (
	cout INT NOT NULL DEFAULT 0,
	depensePA INT NOT NULL DEFAULT 0,
	depensePM INT NOT NULL DEFAULT 0,
	description CHARACTER VARYING(255) NULL,
	distance INT NOT NULL DEFAULT 0,
	dureeHeure REAL NOT NULL DEFAULT 0,
	idRelaisArrive INT NOT NULL,
	idRelaisDepart INT NOT NULL,
	idVoyage INT NOT NULL,
		CONSTRAINT pk_voyages PRIMARY KEY (idvoyage)
);

CREATE TABLE voyageurs (
	chef INT NOT NULL DEFAULT 0,
	dateArrivee INT NULL,
	groupe INT NULL,
	idEvenement INT NULL,
	idPerso INT NOT NULL,
	idVehicule INT NOT NULL,
	idVoyage INT NOT NULL,
	idVoyageur INT NOT NULL,
	message CHARACTER VARYING(500) NULL DEFAULT '',
	momentEvent INT NULL,
	montantRancon INT NULL,
	nbCreature INT NULL,
	pourcentageAvancement INT NULL,
	statusVoyage INT NOT NULL DEFAULT 0,
	statusVoyageur INT NOT NULL DEFAULT 0,
		CONSTRAINT pk_voyageurs PRIMARY KEY (idvoyageur)
);

CREATE TABLE wiki_menus (
	elements TEXT NOT NULL,
	id BIGINT NOT NULL,
	titre CHARACTER VARYING(64) NOT NULL DEFAULT '',
		CONSTRAINT pk_wiki_menus PRIMARY KEY (id)
);

CREATE TABLE wiki_textes (
	id BIGINT NOT NULL,
	menus CHARACTER VARYING(255) NOT NULL,
	prefixe CHARACTER VARYING(40) NULL DEFAULT 'none',
	securite SMALLINT NOT NULL DEFAULT 0,
	texte TEXT NOT NULL,
	titre CHARACTER VARYING(64) NOT NULL DEFAULT '',
		CONSTRAINT pk_wiki_textes PRIMARY KEY (id)
);



commit;